FROM node:20-alpine AS deps
WORKDIR /app
RUN apk add --no-cache openssl
COPY package*.json ./
RUN npm install
{{#if isPostgres}}COPY prisma ./prisma/
RUN npx prisma generate{{/if}}

FROM deps AS dev
COPY . .
EXPOSE 3001
CMD ["npm", "run", "start:dev"]

FROM deps AS builder
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
RUN apk add --no-cache openssl
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
{{#if isPostgres}}COPY --from=builder /app/prisma ./prisma{{/if}}
EXPOSE 3001
CMD ["node", "dist/main"]
